[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
solana_amm_index_strategies = "AMM1ndex1oken1asket1rading1trategy1ngine"

[programs.devnet]
solana_amm_index_strategies = "AMM1ndex1oken1asket1rading1trategy1ngine"

[programs.mainnet]
solana_amm_index_strategies = "AMM1ndex1oken1asket1rading1trategy1ngine"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
clone = [
    { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", filename = "spl_token-3.5.0.so" },
]

[[test.validator.account]]
# address = "11111111111111111111111111111111"  # 已迁移到 src/core/constants.rs::PROGRAM_ID
filename = "system_program.json"

[build]
exclude = ["node_modules"]